name: blue
type: kubernetes
endpoint_name: testprivendpoint
model:
  path: ../model/credit-prediction.pkl
code_configuration:
  code: ../model/
  scoring_script: score.py
environment: 
  conda_file: ../model/inference-conda.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
request_settings:
  request_timeout_ms: 3000
  max_queue_wait_ms: 3000
resources:
  requests:
    cpu: "0.1"
    memory: "0.1Gi"
  limits:
    cpu: "0.2"
    memory: "200Mi"
tags:
  tag1: deployment-tag1-value
instance_count: 1
scale_settings:
  type: default
