variables: 
 - template: german-credit-config.yml

trigger: none

pool:
  vmImage: ubuntu-20.04

steps:
  - task: AzurePowerShell@5
    displayName: 'Create API management operation exposing AKS private endpoint'
    inputs:
      azureSubscription: $(ml_workspace_connection)
      scriptType: filePath
      scriptPath: pipelines/scripts/germin-credit-apimoperation.ps1
      scriptArguments:
        -ml_workspace_rg $(ml_workspace_rg) `
        -ml_apim_name $(ml_apim_name) `
        -ml_deployment_name $(ml_deployment_name) `
        -ml_tenant_id $(ml_tenant_id)
      azurePowerShellVersion: latestVersion
      pwsh: true